In [2]:
import numpy
N,M=map(int,input().split())
A=numpy.array([list(map(int,input().split())) for i in range(N)])
B=numpy.array([list(map(int,input().split())) for i in range(N)])
print(A+B)
print(A-B)
print(A*B)
print(A//B)
print(A%B)
print(A**B)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]
